interface TwilioVoiceClient {
  /** Initialize the Twilio plugin. Needs a token generated by your server */
  initialize: (token: string) => void;
  /** Make a call */
  call: (token: string, params: object) => void;
  /** Disconnect the current call */
  disconnect: () => void;
  /** Change speakerphone state */
  setSpeaker: (state: "on" | "off") => void;  
  /** Called when there is an error with the native SDK */
  onError: (error: object) => void;
  /** Called when the client has been initialized  */
  onClientInitialized: (callback: () => void) => void;
  /** Called when the call has been connected / started  */
  onCallDidConnect: (callback: (call: any) => void) => void;
  /** Called when the call has been remotely disconnected / ended  */
  onCallDidDisconnect: (callback: (call: any) => void) => void;
}


interface TwilioPlugin {
  TwilioVoiceClient: TwilioVoiceClient
}

interface Window {
  Twilio: TwilioPlugin;
}

declare var Twilio: TwilioPlugin;

declare module 'Twilio' {
    export = Twilio;
}
